k = ('2', '12', '9', '78', '15', '12')
j = tuple()
m = (12, 1, 4, 7, 8)
print(k)
print('kortejdagi x element soni', k.count('12'))
print('kortejdagi x element indeksi', k.index('78'))
print('kortejdagi x element tekshirish', any(k))
print('kortejdagi x element tekshirish', any(j))
print('max element:', max(k))
print('max element:', min(k))
print('kortej uzunligi:', len(k))
print(sorted(m))
